services:
  tasks_pg:
    image: postgres:15.1
    container_name: tasks_pg
    restart: always
    environment:
      POSTGRES_DB: tasks_db
      POSTGRES_USER: joofe
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432